-- Create tables
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL,
    hash TEXT NOT NULL
);
CREATE UNIQUE INDEX username ON users (username);

CREATE TABLE tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL
);
CREATE UNIQUE INDEX name ON tags (name);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    tags TEXT NOT NULL,
    createdAt DATETIME DEFAULT current_timestamp,
    updatedAt DATETIME DEFAULT current_timestamp,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE stars (
    user_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    UNIQUE(user_id, post_id) ON CONFLICT IGNORE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- Insert users
INSERT INTO users (username, hash) VALUES ('Jamie_Martinez84', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Taylor_Brown92', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Davis48', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Hernandez43', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Martinez69', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Martinez5', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Morgan_Miller83', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Davis86', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Smith34', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Smith83', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Johnson22', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Miller23', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Jones94', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Jones61', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Williams5', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Robin_Miller75', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Hernandez40', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Smith27', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Jones40', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Jones82', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Taylor_Miller25', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Morgan_Jones53', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Taylor_Johnson87', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Robin_Davis74', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Jamie_Williams25', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Robin_Martinez13', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Brown72', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Taylor_Smith50', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Johnson23', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Johnson26', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Robin_Garcia37', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Quinn_Garcia67', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Brown95', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Jamie_Martinez60', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Hernandez56', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Johnson33', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Robin_Jones53', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Brown88', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Morgan_Jones80', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Garcia83', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Garcia80', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Jordan_Davis18', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Jamie_Miller37', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Drew_Martinez83', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Casey_Davis41', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Hernandez44', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Jordan_Williams34', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Reese_Johnson44', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Alex_Davis45', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('Morgan_Jones54', 'hashed_password');
INSERT INTO users (username, hash) VALUES ('kthezelais', 'scrypt:32768:8:1$50TrSzWrziuSmywX$fdd4f273f27ae201fdd2624955b4effd5f5f2b212f3daa151d5af0b98996dee521721e084fb95f091b37c5b86cb3d7f541e9127eed8cfb19a4feb8747e114bd3');

-- Insert tags
INSERT INTO tags (name) VALUES ('Technology');
INSERT INTO tags (name) VALUES ('Health');
INSERT INTO tags (name) VALUES ('Education');
INSERT INTO tags (name) VALUES ('Environment');
INSERT INTO tags (name) VALUES ('Finance');
INSERT INTO tags (name) VALUES ('Entertainment');
INSERT INTO tags (name) VALUES ('Sports');
INSERT INTO tags (name) VALUES ('Travel');
INSERT INTO tags (name) VALUES ('Food');
INSERT INTO tags (name) VALUES ('Fashion');
INSERT INTO tags (name) VALUES ('Science');
INSERT INTO tags (name) VALUES ('Art');
INSERT INTO tags (name) VALUES ('Music');
INSERT INTO tags (name) VALUES ('Automotive');
INSERT INTO tags (name) VALUES ('Real Estate');
INSERT INTO tags (name) VALUES ('Gaming');
INSERT INTO tags (name) VALUES ('Fitness');
INSERT INTO tags (name) VALUES ('Parenting');
INSERT INTO tags (name) VALUES ('Pets');
INSERT INTO tags (name) VALUES ('DIY');
INSERT INTO tags (name) VALUES ('Crafts');
INSERT INTO tags (name) VALUES ('Photography');
INSERT INTO tags (name) VALUES ('Agriculture');
INSERT INTO tags (name) VALUES ('Energy');
INSERT INTO tags (name) VALUES ('Social Media');
INSERT INTO tags (name) VALUES ('Cryptocurrency');
INSERT INTO tags (name) VALUES ('AI & Machine Learning');
INSERT INTO tags (name) VALUES ('Startups');
INSERT INTO tags (name) VALUES ('Nonprofits');
INSERT INTO tags (name) VALUES ('Space Exploration');

-- Insert posts
INSERT INTO posts (user_id, title, description, tags) VALUES (43, 'Revolutionary Concept #0', 'This is a slightly longer description that explains the idea in a bit more detail.', '27-23-26-24-25');
INSERT INTO posts (user_id, title, description, tags) VALUES (39, 'Revolutionary Concept #1', 'Short description.', '11-23-4');
INSERT INTO posts (user_id, title, description, tags) VALUES (22, 'Brilliant Tool #2', 'Short description.', '3-28-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (45, 'Brilliant Concept #3', 'This is a slightly longer description that explains the idea in a bit more detail.', '3-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (15, 'Innovative Product #4', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '8-15-10-24-5');
INSERT INTO posts (user_id, title, description, tags) VALUES (18, 'Creative Concept #5', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '11-7');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Innovative Product #6', 'This is a slightly longer description that explains the idea in a bit more detail.', '27-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (23, 'Amazing Project #7', 'Short description.', '5-3');
INSERT INTO posts (user_id, title, description, tags) VALUES (44, 'Brilliant Tool #8', 'Short description.', '13-3-25');
INSERT INTO posts (user_id, title, description, tags) VALUES (45, 'Groundbreaking Tool #9', 'Short description.', '15-24-1');
INSERT INTO posts (user_id, title, description, tags) VALUES (38, 'Amazing Idea #10', 'Short description.', '6-2-12-27');
INSERT INTO posts (user_id, title, description, tags) VALUES (20, 'Revolutionary Concept #11', 'Short description.', '15-21-26-4');
INSERT INTO posts (user_id, title, description, tags) VALUES (39, 'Groundbreaking Product #12', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '18-3-0-28');
INSERT INTO posts (user_id, title, description, tags) VALUES (5, 'Amazing Project #13', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '6-19');
INSERT INTO posts (user_id, title, description, tags) VALUES (25, 'Revolutionary Product #14', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '28-22-9-29');
INSERT INTO posts (user_id, title, description, tags) VALUES (15, 'Innovative Solution #15', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '7-9-20-11');
INSERT INTO posts (user_id, title, description, tags) VALUES (30, 'Creative Concept #16', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '28-12-20');
INSERT INTO posts (user_id, title, description, tags) VALUES (6, 'Brilliant Project #17', 'Short description.', '9-0-17-4-2');
INSERT INTO posts (user_id, title, description, tags) VALUES (27, 'Groundbreaking Idea #18', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '17-27-25-18');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Revolutionary Solution #19', 'This is a slightly longer description that explains the idea in a bit more detail.', '18-25-3');
INSERT INTO posts (user_id, title, description, tags) VALUES (35, 'Groundbreaking Project #20', 'Short description.', '12-7-28-23');
INSERT INTO posts (user_id, title, description, tags) VALUES (41, 'Groundbreaking Project #21', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '27');
INSERT INTO posts (user_id, title, description, tags) VALUES (11, 'Groundbreaking Tool #22', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '25-26-21-1-20');
INSERT INTO posts (user_id, title, description, tags) VALUES (7, 'Brilliant Project #23', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '0-13-12-2');
INSERT INTO posts (user_id, title, description, tags) VALUES (16, 'Creative Concept #24', 'Short description.', '27');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Amazing Concept #25', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '24');
INSERT INTO posts (user_id, title, description, tags) VALUES (47, 'Amazing Concept #26', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '26-10-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (16, 'Innovative Solution #27', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '17-15-3-9');
INSERT INTO posts (user_id, title, description, tags) VALUES (46, 'Brilliant Project #28', 'This is a slightly longer description that explains the idea in a bit more detail.', '17');
INSERT INTO posts (user_id, title, description, tags) VALUES (25, 'Amazing Concept #29', 'Short description.', '24-3-23');
INSERT INTO posts (user_id, title, description, tags) VALUES (47, 'Innovative Project #30', 'This is a slightly longer description that explains the idea in a bit more detail.', '9-0-10-1');
INSERT INTO posts (user_id, title, description, tags) VALUES (30, 'Creative Concept #31', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '1');
INSERT INTO posts (user_id, title, description, tags) VALUES (25, 'Brilliant Idea #32', 'Short description.', '13');
INSERT INTO posts (user_id, title, description, tags) VALUES (30, 'Amazing Idea #33', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '9-15');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Brilliant Project #34', 'This is a slightly longer description that explains the idea in a bit more detail.', '28-6-5');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Innovative Solution #35', 'Short description.', '25');
INSERT INTO posts (user_id, title, description, tags) VALUES (23, 'Amazing Idea #36', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '12-16-6-20');
INSERT INTO posts (user_id, title, description, tags) VALUES (30, 'Brilliant Tool #37', 'Short description.', '6');
INSERT INTO posts (user_id, title, description, tags) VALUES (27, 'Brilliant Idea #38', 'Short description.', '6-22-29-21-25');
INSERT INTO posts (user_id, title, description, tags) VALUES (32, 'Innovative Idea #39', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '24');
INSERT INTO posts (user_id, title, description, tags) VALUES (2, 'Innovative Solution #40', 'This is a slightly longer description that explains the idea in a bit more detail.', '11-13');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Innovative Concept #41', 'This is a slightly longer description that explains the idea in a bit more detail.', '26-1-0');
INSERT INTO posts (user_id, title, description, tags) VALUES (10, 'Groundbreaking Idea #42', 'Short description.', '0');
INSERT INTO posts (user_id, title, description, tags) VALUES (18, 'Creative Project #43', 'This is a slightly longer description that explains the idea in a bit more detail.', '14-21-18');
INSERT INTO posts (user_id, title, description, tags) VALUES (40, 'Brilliant Project #44', 'This is a slightly longer description that explains the idea in a bit more detail.', '20-0-17-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (32, 'Groundbreaking Product #45', 'Short description.', '19-3-23');
INSERT INTO posts (user_id, title, description, tags) VALUES (47, 'Innovative Tool #46', 'This is a slightly longer description that explains the idea in a bit more detail.', '10');
INSERT INTO posts (user_id, title, description, tags) VALUES (48, 'Creative Tool #47', 'Short description.', '6-11-29');
INSERT INTO posts (user_id, title, description, tags) VALUES (7, 'Creative Project #48', 'Short description.', '29-20-27');
INSERT INTO posts (user_id, title, description, tags) VALUES (10, 'Amazing Idea #49', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '21-9-4-1-18');
INSERT INTO posts (user_id, title, description, tags) VALUES (22, 'Amazing Concept #50', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '13');
INSERT INTO posts (user_id, title, description, tags) VALUES (44, 'Brilliant Product #51', 'This is a slightly longer description that explains the idea in a bit more detail.', '9-27-13-12-19');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Innovative Idea #52', 'Short description.', '18-17');
INSERT INTO posts (user_id, title, description, tags) VALUES (3, 'Revolutionary Tool #53', 'This is a slightly longer description that explains the idea in a bit more detail.', '17-1-8-7');
INSERT INTO posts (user_id, title, description, tags) VALUES (44, 'Creative Tool #54', 'Short description.', '29');
INSERT INTO posts (user_id, title, description, tags) VALUES (46, 'Amazing Project #55', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '29-21');
INSERT INTO posts (user_id, title, description, tags) VALUES (35, 'Innovative Product #56', 'This is a slightly longer description that explains the idea in a bit more detail.', '1');
INSERT INTO posts (user_id, title, description, tags) VALUES (29, 'Groundbreaking Project #57', 'This is a slightly longer description that explains the idea in a bit more detail.', '3-17');
INSERT INTO posts (user_id, title, description, tags) VALUES (35, 'Amazing Project #58', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '28');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Brilliant Project #59', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '3-19-18');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Brilliant Tool #60', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '12');
INSERT INTO posts (user_id, title, description, tags) VALUES (6, 'Innovative Solution #61', 'Short description.', '1');
INSERT INTO posts (user_id, title, description, tags) VALUES (26, 'Groundbreaking Project #62', 'Short description.', '28');
INSERT INTO posts (user_id, title, description, tags) VALUES (42, 'Brilliant Concept #63', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '23-21-13-27');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Groundbreaking Project #64', 'This is a slightly longer description that explains the idea in a bit more detail.', '6');
INSERT INTO posts (user_id, title, description, tags) VALUES (34, 'Creative Solution #65', 'This is a slightly longer description that explains the idea in a bit more detail.', '16');
INSERT INTO posts (user_id, title, description, tags) VALUES (40, 'Groundbreaking Project #66', 'This is a slightly longer description that explains the idea in a bit more detail.', '16');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Revolutionary Idea #67', 'This is a slightly longer description that explains the idea in a bit more detail.', '27-21-9-20-24');
INSERT INTO posts (user_id, title, description, tags) VALUES (3, 'Brilliant Tool #68', 'This is a slightly longer description that explains the idea in a bit more detail.', '25');
INSERT INTO posts (user_id, title, description, tags) VALUES (44, 'Revolutionary Idea #69', 'Short description.', '5-29');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Amazing Tool #70', 'This is a slightly longer description that explains the idea in a bit more detail.', '4-22-28');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Brilliant Idea #71', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '5-8-2');
INSERT INTO posts (user_id, title, description, tags) VALUES (37, 'Innovative Concept #72', 'Short description.', '26');
INSERT INTO posts (user_id, title, description, tags) VALUES (11, 'Groundbreaking Idea #73', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '27');
INSERT INTO posts (user_id, title, description, tags) VALUES (15, 'Amazing Project #74', 'Short description.', '5');
INSERT INTO posts (user_id, title, description, tags) VALUES (37, 'Brilliant Tool #75', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '1-3-15-21');
INSERT INTO posts (user_id, title, description, tags) VALUES (32, 'Creative Concept #76', 'Short description.', '1');
INSERT INTO posts (user_id, title, description, tags) VALUES (11, 'Creative Project #77', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '23-11-9-18-4');
INSERT INTO posts (user_id, title, description, tags) VALUES (15, 'Creative Tool #78', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '1');
INSERT INTO posts (user_id, title, description, tags) VALUES (28, 'Amazing Concept #79', 'Short description.', '22-11-20-21-24');
INSERT INTO posts (user_id, title, description, tags) VALUES (1, 'Creative Concept #80', 'Short description.', '28-21-23-5');
INSERT INTO posts (user_id, title, description, tags) VALUES (18, 'Groundbreaking Tool #81', 'Short description.', '16-14-13-23-21');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Creative Idea #82', 'This is a slightly longer description that explains the idea in a bit more detail.', '22-19-0-11');
INSERT INTO posts (user_id, title, description, tags) VALUES (26, 'Amazing Project #83', 'Short description.', '11-16-1-25-4');
INSERT INTO posts (user_id, title, description, tags) VALUES (23, 'Revolutionary Product #84', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '24-12-2');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Creative Tool #85', 'Short description.', '16-26-21-8');
INSERT INTO posts (user_id, title, description, tags) VALUES (37, 'Amazing Tool #86', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '23-27-16-18');
INSERT INTO posts (user_id, title, description, tags) VALUES (37, 'Brilliant Idea #87', 'This is a slightly longer description that explains the idea in a bit more detail.', '15-17-10');
INSERT INTO posts (user_id, title, description, tags) VALUES (17, 'Brilliant Product #88', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '10-24');
INSERT INTO posts (user_id, title, description, tags) VALUES (27, 'Revolutionary Product #89', 'Short description.', '0-16-15-2');
INSERT INTO posts (user_id, title, description, tags) VALUES (10, 'Creative Product #90', 'This is a slightly longer description that explains the idea in a bit more detail.', '18-19-0');
INSERT INTO posts (user_id, title, description, tags) VALUES (4, 'Revolutionary Product #91', 'Short description.', '5-21');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Revolutionary Solution #92', 'Short description.', '26');
INSERT INTO posts (user_id, title, description, tags) VALUES (8, 'Revolutionary Product #93', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '22');
INSERT INTO posts (user_id, title, description, tags) VALUES (24, 'Creative Tool #94', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '3-15');
INSERT INTO posts (user_id, title, description, tags) VALUES (42, 'Brilliant Tool #95', 'Short description.', '1-5-23-17-24');
INSERT INTO posts (user_id, title, description, tags) VALUES (21, 'Revolutionary Solution #96', 'Short description.', '2-22-18-13');
INSERT INTO posts (user_id, title, description, tags) VALUES (49, 'Creative Idea #97', 'Short description.', '14-20-25-13-0');
INSERT INTO posts (user_id, title, description, tags) VALUES (11, 'Revolutionary Idea #98', 'Short description.', '20-9-25');
INSERT INTO posts (user_id, title, description, tags) VALUES (14, 'Amazing Concept #99', 'Here is a comprehensive and detailed description of the idea, explaining all aspects and potential impacts, which spans multiple lines to thoroughly discuss the concept.', '0');
INSERT INTO posts (user_id, title, description, tags) VALUES (50, 'Faire un appareil a popo', 'Un appareil qui permet de regarder si on a du caca dans les intestins, voila voila !', '0');

-- Insert stars
INSERT INTO stars (user_id, post_id) VALUES (38, 1);
INSERT INTO stars (user_id, post_id) VALUES (20, 1);
INSERT INTO stars (user_id, post_id) VALUES (25, 1);
INSERT INTO stars (user_id, post_id) VALUES (38, 1);
INSERT INTO stars (user_id, post_id) VALUES (39, 1);
INSERT INTO stars (user_id, post_id) VALUES (29, 1);
INSERT INTO stars (user_id, post_id) VALUES (25, 1);
INSERT INTO stars (user_id, post_id) VALUES (3, 1);
INSERT INTO stars (user_id, post_id) VALUES (44, 1);
INSERT INTO stars (user_id, post_id) VALUES (33, 1);
INSERT INTO stars (user_id, post_id) VALUES (34, 1);
INSERT INTO stars (user_id, post_id) VALUES (2, 1);
INSERT INTO stars (user_id, post_id) VALUES (13, 1);
INSERT INTO stars (user_id, post_id) VALUES (26, 1);
INSERT INTO stars (user_id, post_id) VALUES (9, 1);
INSERT INTO stars (user_id, post_id) VALUES (13, 1);
INSERT INTO stars (user_id, post_id) VALUES (11, 1);
INSERT INTO stars (user_id, post_id) VALUES (16, 1);
INSERT INTO stars (user_id, post_id) VALUES (38, 1);
INSERT INTO stars (user_id, post_id) VALUES (17, 1);
INSERT INTO stars (user_id, post_id) VALUES (6, 1);
INSERT INTO stars (user_id, post_id) VALUES (39, 1);
INSERT INTO stars (user_id, post_id) VALUES (18, 1);
INSERT INTO stars (user_id, post_id) VALUES (1, 1);
INSERT INTO stars (user_id, post_id) VALUES (18, 1);
INSERT INTO stars (user_id, post_id) VALUES (43, 1);
INSERT INTO stars (user_id, post_id) VALUES (27, 1);
INSERT INTO stars (user_id, post_id) VALUES (9, 1);
INSERT INTO stars (user_id, post_id) VALUES (1, 1);
INSERT INTO stars (user_id, post_id) VALUES (35, 1);
INSERT INTO stars (user_id, post_id) VALUES (16, 1);
INSERT INTO stars (user_id, post_id) VALUES (8, 2);
INSERT INTO stars (user_id, post_id) VALUES (45, 3);
INSERT INTO stars (user_id, post_id) VALUES (29, 3);
INSERT INTO stars (user_id, post_id) VALUES (3, 3);
INSERT INTO stars (user_id, post_id) VALUES (29, 3);
INSERT INTO stars (user_id, post_id) VALUES (43, 3);
INSERT INTO stars (user_id, post_id) VALUES (16, 3);
INSERT INTO stars (user_id, post_id) VALUES (42, 3);
INSERT INTO stars (user_id, post_id) VALUES (36, 3);
INSERT INTO stars (user_id, post_id) VALUES (40, 3);
INSERT INTO stars (user_id, post_id) VALUES (45, 3);
INSERT INTO stars (user_id, post_id) VALUES (24, 3);
INSERT INTO stars (user_id, post_id) VALUES (20, 3);
INSERT INTO stars (user_id, post_id) VALUES (10, 3);
INSERT INTO stars (user_id, post_id) VALUES (34, 3);
INSERT INTO stars (user_id, post_id) VALUES (43, 3);
INSERT INTO stars (user_id, post_id) VALUES (25, 4);
INSERT INTO stars (user_id, post_id) VALUES (41, 4);
INSERT INTO stars (user_id, post_id) VALUES (40, 4);
INSERT INTO stars (user_id, post_id) VALUES (47, 4);
INSERT INTO stars (user_id, post_id) VALUES (49, 4);
INSERT INTO stars (user_id, post_id) VALUES (29, 4);
INSERT INTO stars (user_id, post_id) VALUES (4, 4);
INSERT INTO stars (user_id, post_id) VALUES (40, 4);
INSERT INTO stars (user_id, post_id) VALUES (29, 4);
INSERT INTO stars (user_id, post_id) VALUES (7, 4);
INSERT INTO stars (user_id, post_id) VALUES (12, 4);
INSERT INTO stars (user_id, post_id) VALUES (25, 5);
INSERT INTO stars (user_id, post_id) VALUES (15, 6);
INSERT INTO stars (user_id, post_id) VALUES (30, 6);
INSERT INTO stars (user_id, post_id) VALUES (46, 6);
INSERT INTO stars (user_id, post_id) VALUES (41, 6);
INSERT INTO stars (user_id, post_id) VALUES (12, 7);
INSERT INTO stars (user_id, post_id) VALUES (19, 7);
INSERT INTO stars (user_id, post_id) VALUES (35, 7);
INSERT INTO stars (user_id, post_id) VALUES (3, 7);
INSERT INTO stars (user_id, post_id) VALUES (42, 7);
INSERT INTO stars (user_id, post_id) VALUES (40, 7);
INSERT INTO stars (user_id, post_id) VALUES (35, 7);
INSERT INTO stars (user_id, post_id) VALUES (22, 7);
INSERT INTO stars (user_id, post_id) VALUES (34, 7);
INSERT INTO stars (user_id, post_id) VALUES (10, 7);
INSERT INTO stars (user_id, post_id) VALUES (40, 7);
INSERT INTO stars (user_id, post_id) VALUES (48, 7);
INSERT INTO stars (user_id, post_id) VALUES (33, 7);
INSERT INTO stars (user_id, post_id) VALUES (29, 7);
INSERT INTO stars (user_id, post_id) VALUES (16, 7);
INSERT INTO stars (user_id, post_id) VALUES (10, 7);
INSERT INTO stars (user_id, post_id) VALUES (2, 8);
INSERT INTO stars (user_id, post_id) VALUES (17, 8);
INSERT INTO stars (user_id, post_id) VALUES (33, 8);
INSERT INTO stars (user_id, post_id) VALUES (17, 8);
INSERT INTO stars (user_id, post_id) VALUES (39, 8);
INSERT INTO stars (user_id, post_id) VALUES (9, 8);
INSERT INTO stars (user_id, post_id) VALUES (9, 8);
INSERT INTO stars (user_id, post_id) VALUES (43, 8);
INSERT INTO stars (user_id, post_id) VALUES (24, 8);
INSERT INTO stars (user_id, post_id) VALUES (43, 8);
INSERT INTO stars (user_id, post_id) VALUES (32, 9);
INSERT INTO stars (user_id, post_id) VALUES (30, 9);
INSERT INTO stars (user_id, post_id) VALUES (27, 9);
INSERT INTO stars (user_id, post_id) VALUES (1, 9);
INSERT INTO stars (user_id, post_id) VALUES (28, 9);
INSERT INTO stars (user_id, post_id) VALUES (44, 9);
INSERT INTO stars (user_id, post_id) VALUES (23, 9);
INSERT INTO stars (user_id, post_id) VALUES (16, 9);
INSERT INTO stars (user_id, post_id) VALUES (19, 9);
INSERT INTO stars (user_id, post_id) VALUES (35, 9);
INSERT INTO stars (user_id, post_id) VALUES (48, 9);
INSERT INTO stars (user_id, post_id) VALUES (18, 9);
INSERT INTO stars (user_id, post_id) VALUES (35, 9);
INSERT INTO stars (user_id, post_id) VALUES (36, 9);
INSERT INTO stars (user_id, post_id) VALUES (6, 9);
INSERT INTO stars (user_id, post_id) VALUES (39, 9);
INSERT INTO stars (user_id, post_id) VALUES (1, 9);
INSERT INTO stars (user_id, post_id) VALUES (22, 9);
INSERT INTO stars (user_id, post_id) VALUES (25, 9);
INSERT INTO stars (user_id, post_id) VALUES (17, 9);
INSERT INTO stars (user_id, post_id) VALUES (25, 11);
INSERT INTO stars (user_id, post_id) VALUES (9, 11);
INSERT INTO stars (user_id, post_id) VALUES (31, 11);
INSERT INTO stars (user_id, post_id) VALUES (19, 11);
INSERT INTO stars (user_id, post_id) VALUES (16, 11);
INSERT INTO stars (user_id, post_id) VALUES (20, 11);
INSERT INTO stars (user_id, post_id) VALUES (7, 11);
INSERT INTO stars (user_id, post_id) VALUES (41, 11);
INSERT INTO stars (user_id, post_id) VALUES (20, 11);
INSERT INTO stars (user_id, post_id) VALUES (24, 11);
INSERT INTO stars (user_id, post_id) VALUES (29, 11);
INSERT INTO stars (user_id, post_id) VALUES (34, 11);
INSERT INTO stars (user_id, post_id) VALUES (29, 11);
INSERT INTO stars (user_id, post_id) VALUES (18, 11);
INSERT INTO stars (user_id, post_id) VALUES (38, 11);
INSERT INTO stars (user_id, post_id) VALUES (1, 11);
INSERT INTO stars (user_id, post_id) VALUES (21, 11);
INSERT INTO stars (user_id, post_id) VALUES (28, 11);
INSERT INTO stars (user_id, post_id) VALUES (17, 11);
INSERT INTO stars (user_id, post_id) VALUES (17, 11);
INSERT INTO stars (user_id, post_id) VALUES (23, 11);
INSERT INTO stars (user_id, post_id) VALUES (24, 11);
INSERT INTO stars (user_id, post_id) VALUES (45, 11);
INSERT INTO stars (user_id, post_id) VALUES (42, 11);
INSERT INTO stars (user_id, post_id) VALUES (27, 11);
INSERT INTO stars (user_id, post_id) VALUES (37, 11);
INSERT INTO stars (user_id, post_id) VALUES (34, 11);
INSERT INTO stars (user_id, post_id) VALUES (48, 11);
INSERT INTO stars (user_id, post_id) VALUES (32, 11);
INSERT INTO stars (user_id, post_id) VALUES (10, 11);
INSERT INTO stars (user_id, post_id) VALUES (24, 11);
INSERT INTO stars (user_id, post_id) VALUES (11, 11);
INSERT INTO stars (user_id, post_id) VALUES (21, 11);
INSERT INTO stars (user_id, post_id) VALUES (7, 11);
INSERT INTO stars (user_id, post_id) VALUES (40, 11);
INSERT INTO stars (user_id, post_id) VALUES (3, 11);
INSERT INTO stars (user_id, post_id) VALUES (20, 11);
INSERT INTO stars (user_id, post_id) VALUES (3, 12);
INSERT INTO stars (user_id, post_id) VALUES (1, 12);
INSERT INTO stars (user_id, post_id) VALUES (13, 12);
INSERT INTO stars (user_id, post_id) VALUES (44, 13);
INSERT INTO stars (user_id, post_id) VALUES (27, 13);
INSERT INTO stars (user_id, post_id) VALUES (23, 13);
INSERT INTO stars (user_id, post_id) VALUES (6, 13);
INSERT INTO stars (user_id, post_id) VALUES (41, 13);
INSERT INTO stars (user_id, post_id) VALUES (43, 13);
INSERT INTO stars (user_id, post_id) VALUES (1, 14);
INSERT INTO stars (user_id, post_id) VALUES (23, 14);
INSERT INTO stars (user_id, post_id) VALUES (41, 14);
INSERT INTO stars (user_id, post_id) VALUES (1, 14);
INSERT INTO stars (user_id, post_id) VALUES (22, 14);
INSERT INTO stars (user_id, post_id) VALUES (21, 14);
INSERT INTO stars (user_id, post_id) VALUES (21, 14);
INSERT INTO stars (user_id, post_id) VALUES (28, 14);
INSERT INTO stars (user_id, post_id) VALUES (11, 14);
INSERT INTO stars (user_id, post_id) VALUES (23, 14);
INSERT INTO stars (user_id, post_id) VALUES (22, 14);
INSERT INTO stars (user_id, post_id) VALUES (10, 14);
INSERT INTO stars (user_id, post_id) VALUES (38, 14);
INSERT INTO stars (user_id, post_id) VALUES (16, 14);
INSERT INTO stars (user_id, post_id) VALUES (25, 14);
INSERT INTO stars (user_id, post_id) VALUES (14, 15);
INSERT INTO stars (user_id, post_id) VALUES (1, 15);
INSERT INTO stars (user_id, post_id) VALUES (6, 15);
INSERT INTO stars (user_id, post_id) VALUES (41, 15);
INSERT INTO stars (user_id, post_id) VALUES (10, 15);
INSERT INTO stars (user_id, post_id) VALUES (44, 15);
INSERT INTO stars (user_id, post_id) VALUES (41, 15);
INSERT INTO stars (user_id, post_id) VALUES (29, 15);
INSERT INTO stars (user_id, post_id) VALUES (42, 15);
INSERT INTO stars (user_id, post_id) VALUES (29, 15);
INSERT INTO stars (user_id, post_id) VALUES (37, 15);
INSERT INTO stars (user_id, post_id) VALUES (13, 15);
INSERT INTO stars (user_id, post_id) VALUES (1, 15);
INSERT INTO stars (user_id, post_id) VALUES (47, 15);
INSERT INTO stars (user_id, post_id) VALUES (28, 15);
INSERT INTO stars (user_id, post_id) VALUES (31, 15);
INSERT INTO stars (user_id, post_id) VALUES (22, 15);
INSERT INTO stars (user_id, post_id) VALUES (35, 16);
INSERT INTO stars (user_id, post_id) VALUES (4, 16);
INSERT INTO stars (user_id, post_id) VALUES (2, 16);
INSERT INTO stars (user_id, post_id) VALUES (38, 16);
INSERT INTO stars (user_id, post_id) VALUES (30, 16);
INSERT INTO stars (user_id, post_id) VALUES (21, 16);
INSERT INTO stars (user_id, post_id) VALUES (34, 16);
INSERT INTO stars (user_id, post_id) VALUES (40, 16);
INSERT INTO stars (user_id, post_id) VALUES (11, 16);
INSERT INTO stars (user_id, post_id) VALUES (41, 16);
INSERT INTO stars (user_id, post_id) VALUES (22, 16);
INSERT INTO stars (user_id, post_id) VALUES (49, 16);
INSERT INTO stars (user_id, post_id) VALUES (44, 16);
INSERT INTO stars (user_id, post_id) VALUES (48, 16);
INSERT INTO stars (user_id, post_id) VALUES (35, 16);
INSERT INTO stars (user_id, post_id) VALUES (46, 16);
INSERT INTO stars (user_id, post_id) VALUES (8, 17);
INSERT INTO stars (user_id, post_id) VALUES (4, 17);
INSERT INTO stars (user_id, post_id) VALUES (18, 17);
INSERT INTO stars (user_id, post_id) VALUES (33, 17);
INSERT INTO stars (user_id, post_id) VALUES (39, 17);
INSERT INTO stars (user_id, post_id) VALUES (25, 17);
INSERT INTO stars (user_id, post_id) VALUES (35, 17);
INSERT INTO stars (user_id, post_id) VALUES (31, 17);
INSERT INTO stars (user_id, post_id) VALUES (34, 18);
INSERT INTO stars (user_id, post_id) VALUES (40, 18);
INSERT INTO stars (user_id, post_id) VALUES (37, 18);
INSERT INTO stars (user_id, post_id) VALUES (42, 18);
INSERT INTO stars (user_id, post_id) VALUES (41, 18);
INSERT INTO stars (user_id, post_id) VALUES (3, 18);
INSERT INTO stars (user_id, post_id) VALUES (15, 18);
INSERT INTO stars (user_id, post_id) VALUES (30, 18);
INSERT INTO stars (user_id, post_id) VALUES (46, 18);
INSERT INTO stars (user_id, post_id) VALUES (30, 18);
INSERT INTO stars (user_id, post_id) VALUES (26, 18);
INSERT INTO stars (user_id, post_id) VALUES (45, 19);
INSERT INTO stars (user_id, post_id) VALUES (45, 19);
INSERT INTO stars (user_id, post_id) VALUES (1, 19);
INSERT INTO stars (user_id, post_id) VALUES (44, 19);
INSERT INTO stars (user_id, post_id) VALUES (39, 19);
INSERT INTO stars (user_id, post_id) VALUES (12, 19);
INSERT INTO stars (user_id, post_id) VALUES (47, 19);
INSERT INTO stars (user_id, post_id) VALUES (4, 19);
INSERT INTO stars (user_id, post_id) VALUES (28, 19);
INSERT INTO stars (user_id, post_id) VALUES (6, 19);
INSERT INTO stars (user_id, post_id) VALUES (1, 19);
INSERT INTO stars (user_id, post_id) VALUES (26, 19);
INSERT INTO stars (user_id, post_id) VALUES (1, 19);
INSERT INTO stars (user_id, post_id) VALUES (8, 19);
INSERT INTO stars (user_id, post_id) VALUES (1, 19);
INSERT INTO stars (user_id, post_id) VALUES (24, 19);
INSERT INTO stars (user_id, post_id) VALUES (31, 19);
INSERT INTO stars (user_id, post_id) VALUES (24, 19);
INSERT INTO stars (user_id, post_id) VALUES (17, 21);
INSERT INTO stars (user_id, post_id) VALUES (12, 21);
INSERT INTO stars (user_id, post_id) VALUES (42, 21);
INSERT INTO stars (user_id, post_id) VALUES (43, 21);
INSERT INTO stars (user_id, post_id) VALUES (44, 21);
INSERT INTO stars (user_id, post_id) VALUES (11, 21);
INSERT INTO stars (user_id, post_id) VALUES (23, 21);
INSERT INTO stars (user_id, post_id) VALUES (24, 21);
INSERT INTO stars (user_id, post_id) VALUES (49, 21);
INSERT INTO stars (user_id, post_id) VALUES (44, 21);
INSERT INTO stars (user_id, post_id) VALUES (15, 21);
INSERT INTO stars (user_id, post_id) VALUES (1, 21);
INSERT INTO stars (user_id, post_id) VALUES (18, 21);
INSERT INTO stars (user_id, post_id) VALUES (37, 21);
INSERT INTO stars (user_id, post_id) VALUES (49, 22);
INSERT INTO stars (user_id, post_id) VALUES (17, 22);
INSERT INTO stars (user_id, post_id) VALUES (21, 22);
INSERT INTO stars (user_id, post_id) VALUES (45, 22);
INSERT INTO stars (user_id, post_id) VALUES (48, 22);
INSERT INTO stars (user_id, post_id) VALUES (6, 22);
INSERT INTO stars (user_id, post_id) VALUES (49, 22);
INSERT INTO stars (user_id, post_id) VALUES (41, 22);
INSERT INTO stars (user_id, post_id) VALUES (16, 22);
INSERT INTO stars (user_id, post_id) VALUES (10, 22);
INSERT INTO stars (user_id, post_id) VALUES (48, 22);
INSERT INTO stars (user_id, post_id) VALUES (49, 22);
INSERT INTO stars (user_id, post_id) VALUES (34, 23);
INSERT INTO stars (user_id, post_id) VALUES (2, 23);
INSERT INTO stars (user_id, post_id) VALUES (10, 23);
INSERT INTO stars (user_id, post_id) VALUES (9, 23);
INSERT INTO stars (user_id, post_id) VALUES (1, 23);
INSERT INTO stars (user_id, post_id) VALUES (19, 23);
INSERT INTO stars (user_id, post_id) VALUES (7, 23);
INSERT INTO stars (user_id, post_id) VALUES (33, 23);
INSERT INTO stars (user_id, post_id) VALUES (33, 23);
INSERT INTO stars (user_id, post_id) VALUES (15, 23);
INSERT INTO stars (user_id, post_id) VALUES (31, 23);
INSERT INTO stars (user_id, post_id) VALUES (11, 23);
INSERT INTO stars (user_id, post_id) VALUES (27, 23);
INSERT INTO stars (user_id, post_id) VALUES (22, 23);
INSERT INTO stars (user_id, post_id) VALUES (5, 23);
INSERT INTO stars (user_id, post_id) VALUES (32, 24);
INSERT INTO stars (user_id, post_id) VALUES (40, 24);
INSERT INTO stars (user_id, post_id) VALUES (49, 24);
INSERT INTO stars (user_id, post_id) VALUES (40, 24);
INSERT INTO stars (user_id, post_id) VALUES (6, 24);
INSERT INTO stars (user_id, post_id) VALUES (31, 24);
INSERT INTO stars (user_id, post_id) VALUES (20, 24);
INSERT INTO stars (user_id, post_id) VALUES (16, 24);
INSERT INTO stars (user_id, post_id) VALUES (1, 24);
INSERT INTO stars (user_id, post_id) VALUES (33, 24);
INSERT INTO stars (user_id, post_id) VALUES (29, 24);
INSERT INTO stars (user_id, post_id) VALUES (7, 24);
INSERT INTO stars (user_id, post_id) VALUES (40, 24);
INSERT INTO stars (user_id, post_id) VALUES (17, 24);
INSERT INTO stars (user_id, post_id) VALUES (48, 24);
INSERT INTO stars (user_id, post_id) VALUES (10, 24);
INSERT INTO stars (user_id, post_id) VALUES (8, 24);
INSERT INTO stars (user_id, post_id) VALUES (31, 25);
INSERT INTO stars (user_id, post_id) VALUES (41, 25);
INSERT INTO stars (user_id, post_id) VALUES (22, 25);
INSERT INTO stars (user_id, post_id) VALUES (43, 25);
INSERT INTO stars (user_id, post_id) VALUES (2, 25);
INSERT INTO stars (user_id, post_id) VALUES (21, 25);
INSERT INTO stars (user_id, post_id) VALUES (36, 26);
INSERT INTO stars (user_id, post_id) VALUES (43, 26);
INSERT INTO stars (user_id, post_id) VALUES (11, 26);
INSERT INTO stars (user_id, post_id) VALUES (23, 26);
INSERT INTO stars (user_id, post_id) VALUES (35, 26);
INSERT INTO stars (user_id, post_id) VALUES (44, 26);
INSERT INTO stars (user_id, post_id) VALUES (16, 26);
INSERT INTO stars (user_id, post_id) VALUES (27, 26);
INSERT INTO stars (user_id, post_id) VALUES (30, 26);
INSERT INTO stars (user_id, post_id) VALUES (7, 26);
INSERT INTO stars (user_id, post_id) VALUES (32, 26);
INSERT INTO stars (user_id, post_id) VALUES (34, 26);
INSERT INTO stars (user_id, post_id) VALUES (36, 26);
INSERT INTO stars (user_id, post_id) VALUES (5, 26);
INSERT INTO stars (user_id, post_id) VALUES (46, 27);
INSERT INTO stars (user_id, post_id) VALUES (22, 27);
INSERT INTO stars (user_id, post_id) VALUES (36, 27);
INSERT INTO stars (user_id, post_id) VALUES (20, 27);
INSERT INTO stars (user_id, post_id) VALUES (32, 27);
INSERT INTO stars (user_id, post_id) VALUES (40, 27);
INSERT INTO stars (user_id, post_id) VALUES (7, 27);
INSERT INTO stars (user_id, post_id) VALUES (9, 27);
INSERT INTO stars (user_id, post_id) VALUES (43, 27);
INSERT INTO stars (user_id, post_id) VALUES (34, 28);
INSERT INTO stars (user_id, post_id) VALUES (46, 28);
INSERT INTO stars (user_id, post_id) VALUES (27, 28);
INSERT INTO stars (user_id, post_id) VALUES (37, 28);
INSERT INTO stars (user_id, post_id) VALUES (2, 28);
INSERT INTO stars (user_id, post_id) VALUES (46, 28);
INSERT INTO stars (user_id, post_id) VALUES (1, 28);
INSERT INTO stars (user_id, post_id) VALUES (25, 28);
INSERT INTO stars (user_id, post_id) VALUES (8, 28);
INSERT INTO stars (user_id, post_id) VALUES (22, 28);
INSERT INTO stars (user_id, post_id) VALUES (47, 28);
INSERT INTO stars (user_id, post_id) VALUES (38, 28);
INSERT INTO stars (user_id, post_id) VALUES (23, 28);
INSERT INTO stars (user_id, post_id) VALUES (36, 28);
INSERT INTO stars (user_id, post_id) VALUES (48, 29);
INSERT INTO stars (user_id, post_id) VALUES (26, 29);
INSERT INTO stars (user_id, post_id) VALUES (19, 29);
INSERT INTO stars (user_id, post_id) VALUES (18, 29);
INSERT INTO stars (user_id, post_id) VALUES (33, 31);
INSERT INTO stars (user_id, post_id) VALUES (11, 31);
INSERT INTO stars (user_id, post_id) VALUES (2, 31);
INSERT INTO stars (user_id, post_id) VALUES (19, 31);
INSERT INTO stars (user_id, post_id) VALUES (17, 31);
INSERT INTO stars (user_id, post_id) VALUES (25, 31);
INSERT INTO stars (user_id, post_id) VALUES (6, 31);
INSERT INTO stars (user_id, post_id) VALUES (17, 31);
INSERT INTO stars (user_id, post_id) VALUES (9, 31);
INSERT INTO stars (user_id, post_id) VALUES (39, 31);
INSERT INTO stars (user_id, post_id) VALUES (42, 32);
INSERT INTO stars (user_id, post_id) VALUES (27, 32);
INSERT INTO stars (user_id, post_id) VALUES (44, 32);
INSERT INTO stars (user_id, post_id) VALUES (21, 32);
INSERT INTO stars (user_id, post_id) VALUES (46, 32);
INSERT INTO stars (user_id, post_id) VALUES (47, 33);
INSERT INTO stars (user_id, post_id) VALUES (35, 33);
INSERT INTO stars (user_id, post_id) VALUES (31, 33);
INSERT INTO stars (user_id, post_id) VALUES (43, 33);
INSERT INTO stars (user_id, post_id) VALUES (7, 33);
INSERT INTO stars (user_id, post_id) VALUES (8, 33);
INSERT INTO stars (user_id, post_id) VALUES (42, 33);
INSERT INTO stars (user_id, post_id) VALUES (12, 33);
INSERT INTO stars (user_id, post_id) VALUES (39, 33);
INSERT INTO stars (user_id, post_id) VALUES (36, 33);
INSERT INTO stars (user_id, post_id) VALUES (38, 33);
INSERT INTO stars (user_id, post_id) VALUES (24, 33);
INSERT INTO stars (user_id, post_id) VALUES (42, 34);
INSERT INTO stars (user_id, post_id) VALUES (30, 34);
INSERT INTO stars (user_id, post_id) VALUES (31, 34);
INSERT INTO stars (user_id, post_id) VALUES (30, 34);
INSERT INTO stars (user_id, post_id) VALUES (15, 34);
INSERT INTO stars (user_id, post_id) VALUES (36, 34);
INSERT INTO stars (user_id, post_id) VALUES (24, 34);
INSERT INTO stars (user_id, post_id) VALUES (28, 34);
INSERT INTO stars (user_id, post_id) VALUES (35, 34);
INSERT INTO stars (user_id, post_id) VALUES (37, 34);
INSERT INTO stars (user_id, post_id) VALUES (1, 35);
INSERT INTO stars (user_id, post_id) VALUES (47, 35);
INSERT INTO stars (user_id, post_id) VALUES (46, 35);
INSERT INTO stars (user_id, post_id) VALUES (40, 35);
INSERT INTO stars (user_id, post_id) VALUES (36, 35);
INSERT INTO stars (user_id, post_id) VALUES (33, 36);
INSERT INTO stars (user_id, post_id) VALUES (30, 36);
INSERT INTO stars (user_id, post_id) VALUES (48, 36);
INSERT INTO stars (user_id, post_id) VALUES (16, 36);
INSERT INTO stars (user_id, post_id) VALUES (1, 36);
INSERT INTO stars (user_id, post_id) VALUES (33, 36);
INSERT INTO stars (user_id, post_id) VALUES (18, 36);
INSERT INTO stars (user_id, post_id) VALUES (15, 36);
INSERT INTO stars (user_id, post_id) VALUES (48, 36);
INSERT INTO stars (user_id, post_id) VALUES (31, 36);
INSERT INTO stars (user_id, post_id) VALUES (36, 36);
INSERT INTO stars (user_id, post_id) VALUES (48, 36);
INSERT INTO stars (user_id, post_id) VALUES (28, 37);
INSERT INTO stars (user_id, post_id) VALUES (33, 37);
INSERT INTO stars (user_id, post_id) VALUES (46, 38);
INSERT INTO stars (user_id, post_id) VALUES (44, 38);
INSERT INTO stars (user_id, post_id) VALUES (28, 38);
INSERT INTO stars (user_id, post_id) VALUES (1, 38);
INSERT INTO stars (user_id, post_id) VALUES (47, 38);
INSERT INTO stars (user_id, post_id) VALUES (12, 39);
INSERT INTO stars (user_id, post_id) VALUES (10, 39);
INSERT INTO stars (user_id, post_id) VALUES (22, 39);
INSERT INTO stars (user_id, post_id) VALUES (21, 41);
INSERT INTO stars (user_id, post_id) VALUES (30, 41);
INSERT INTO stars (user_id, post_id) VALUES (47, 41);
INSERT INTO stars (user_id, post_id) VALUES (4, 41);
INSERT INTO stars (user_id, post_id) VALUES (12, 41);
INSERT INTO stars (user_id, post_id) VALUES (5, 41);
INSERT INTO stars (user_id, post_id) VALUES (14, 41);
INSERT INTO stars (user_id, post_id) VALUES (7, 41);
INSERT INTO stars (user_id, post_id) VALUES (49, 41);
INSERT INTO stars (user_id, post_id) VALUES (46, 41);
INSERT INTO stars (user_id, post_id) VALUES (12, 41);
INSERT INTO stars (user_id, post_id) VALUES (45, 41);
INSERT INTO stars (user_id, post_id) VALUES (1, 41);
INSERT INTO stars (user_id, post_id) VALUES (36, 41);
INSERT INTO stars (user_id, post_id) VALUES (19, 41);
INSERT INTO stars (user_id, post_id) VALUES (14, 41);
INSERT INTO stars (user_id, post_id) VALUES (19, 41);
INSERT INTO stars (user_id, post_id) VALUES (40, 41);
INSERT INTO stars (user_id, post_id) VALUES (44, 41);
INSERT INTO stars (user_id, post_id) VALUES (16, 41);
INSERT INTO stars (user_id, post_id) VALUES (6, 41);
INSERT INTO stars (user_id, post_id) VALUES (26, 41);
INSERT INTO stars (user_id, post_id) VALUES (9, 41);
INSERT INTO stars (user_id, post_id) VALUES (46, 41);
INSERT INTO stars (user_id, post_id) VALUES (26, 41);
INSERT INTO stars (user_id, post_id) VALUES (11, 41);
INSERT INTO stars (user_id, post_id) VALUES (4, 41);
INSERT INTO stars (user_id, post_id) VALUES (10, 41);
INSERT INTO stars (user_id, post_id) VALUES (12, 41);
INSERT INTO stars (user_id, post_id) VALUES (23, 41);
INSERT INTO stars (user_id, post_id) VALUES (5, 41);
INSERT INTO stars (user_id, post_id) VALUES (22, 42);
INSERT INTO stars (user_id, post_id) VALUES (46, 42);
INSERT INTO stars (user_id, post_id) VALUES (30, 42);
INSERT INTO stars (user_id, post_id) VALUES (45, 42);
INSERT INTO stars (user_id, post_id) VALUES (8, 42);
INSERT INTO stars (user_id, post_id) VALUES (46, 42);
INSERT INTO stars (user_id, post_id) VALUES (20, 42);
INSERT INTO stars (user_id, post_id) VALUES (31, 42);
INSERT INTO stars (user_id, post_id) VALUES (33, 42);
INSERT INTO stars (user_id, post_id) VALUES (46, 42);
INSERT INTO stars (user_id, post_id) VALUES (32, 42);
INSERT INTO stars (user_id, post_id) VALUES (14, 42);
INSERT INTO stars (user_id, post_id) VALUES (11, 42);
INSERT INTO stars (user_id, post_id) VALUES (40, 42);
INSERT INTO stars (user_id, post_id) VALUES (48, 42);
INSERT INTO stars (user_id, post_id) VALUES (15, 42);
INSERT INTO stars (user_id, post_id) VALUES (8, 42);
INSERT INTO stars (user_id, post_id) VALUES (26, 42);
INSERT INTO stars (user_id, post_id) VALUES (36, 42);
INSERT INTO stars (user_id, post_id) VALUES (17, 42);
INSERT INTO stars (user_id, post_id) VALUES (32, 43);
INSERT INTO stars (user_id, post_id) VALUES (47, 43);
INSERT INTO stars (user_id, post_id) VALUES (42, 43);
INSERT INTO stars (user_id, post_id) VALUES (45, 43);
INSERT INTO stars (user_id, post_id) VALUES (6, 43);
INSERT INTO stars (user_id, post_id) VALUES (35, 43);
INSERT INTO stars (user_id, post_id) VALUES (47, 43);
INSERT INTO stars (user_id, post_id) VALUES (15, 43);
INSERT INTO stars (user_id, post_id) VALUES (29, 43);
INSERT INTO stars (user_id, post_id) VALUES (11, 43);
INSERT INTO stars (user_id, post_id) VALUES (12, 43);
INSERT INTO stars (user_id, post_id) VALUES (41, 44);
INSERT INTO stars (user_id, post_id) VALUES (34, 44);
INSERT INTO stars (user_id, post_id) VALUES (6, 44);
INSERT INTO stars (user_id, post_id) VALUES (15, 44);
INSERT INTO stars (user_id, post_id) VALUES (10, 44);
INSERT INTO stars (user_id, post_id) VALUES (47, 44);
INSERT INTO stars (user_id, post_id) VALUES (6, 45);
INSERT INTO stars (user_id, post_id) VALUES (42, 45);
INSERT INTO stars (user_id, post_id) VALUES (37, 45);
INSERT INTO stars (user_id, post_id) VALUES (5, 45);
INSERT INTO stars (user_id, post_id) VALUES (1, 45);
INSERT INTO stars (user_id, post_id) VALUES (41, 45);
INSERT INTO stars (user_id, post_id) VALUES (1, 45);
INSERT INTO stars (user_id, post_id) VALUES (29, 45);
INSERT INTO stars (user_id, post_id) VALUES (14, 45);
INSERT INTO stars (user_id, post_id) VALUES (30, 45);
INSERT INTO stars (user_id, post_id) VALUES (23, 45);
INSERT INTO stars (user_id, post_id) VALUES (3, 45);
INSERT INTO stars (user_id, post_id) VALUES (11, 45);
INSERT INTO stars (user_id, post_id) VALUES (39, 45);
INSERT INTO stars (user_id, post_id) VALUES (15, 45);
INSERT INTO stars (user_id, post_id) VALUES (44, 45);
INSERT INTO stars (user_id, post_id) VALUES (33, 45);
INSERT INTO stars (user_id, post_id) VALUES (30, 45);
INSERT INTO stars (user_id, post_id) VALUES (48, 45);
INSERT INTO stars (user_id, post_id) VALUES (24, 46);
INSERT INTO stars (user_id, post_id) VALUES (28, 46);
INSERT INTO stars (user_id, post_id) VALUES (6, 46);
INSERT INTO stars (user_id, post_id) VALUES (27, 46);
INSERT INTO stars (user_id, post_id) VALUES (34, 46);
INSERT INTO stars (user_id, post_id) VALUES (9, 47);
INSERT INTO stars (user_id, post_id) VALUES (37, 47);
INSERT INTO stars (user_id, post_id) VALUES (45, 47);
INSERT INTO stars (user_id, post_id) VALUES (9, 47);
INSERT INTO stars (user_id, post_id) VALUES (33, 47);
INSERT INTO stars (user_id, post_id) VALUES (9, 47);
INSERT INTO stars (user_id, post_id) VALUES (14, 47);
INSERT INTO stars (user_id, post_id) VALUES (45, 47);
INSERT INTO stars (user_id, post_id) VALUES (20, 47);
INSERT INTO stars (user_id, post_id) VALUES (23, 47);
INSERT INTO stars (user_id, post_id) VALUES (12, 49);
INSERT INTO stars (user_id, post_id) VALUES (24, 51);
INSERT INTO stars (user_id, post_id) VALUES (38, 51);
INSERT INTO stars (user_id, post_id) VALUES (21, 51);
INSERT INTO stars (user_id, post_id) VALUES (21, 51);
INSERT INTO stars (user_id, post_id) VALUES (10, 51);
INSERT INTO stars (user_id, post_id) VALUES (11, 51);
INSERT INTO stars (user_id, post_id) VALUES (33, 51);
INSERT INTO stars (user_id, post_id) VALUES (9, 51);
INSERT INTO stars (user_id, post_id) VALUES (38, 51);
INSERT INTO stars (user_id, post_id) VALUES (4, 51);
INSERT INTO stars (user_id, post_id) VALUES (5, 51);
INSERT INTO stars (user_id, post_id) VALUES (15, 52);
INSERT INTO stars (user_id, post_id) VALUES (7, 52);
INSERT INTO stars (user_id, post_id) VALUES (16, 52);
INSERT INTO stars (user_id, post_id) VALUES (47, 52);
INSERT INTO stars (user_id, post_id) VALUES (34, 52);
INSERT INTO stars (user_id, post_id) VALUES (43, 52);
INSERT INTO stars (user_id, post_id) VALUES (5, 52);
INSERT INTO stars (user_id, post_id) VALUES (34, 52);
INSERT INTO stars (user_id, post_id) VALUES (11, 52);
INSERT INTO stars (user_id, post_id) VALUES (5, 52);
INSERT INTO stars (user_id, post_id) VALUES (1, 53);
INSERT INTO stars (user_id, post_id) VALUES (18, 53);
INSERT INTO stars (user_id, post_id) VALUES (1, 53);
INSERT INTO stars (user_id, post_id) VALUES (15, 53);
INSERT INTO stars (user_id, post_id) VALUES (41, 53);
INSERT INTO stars (user_id, post_id) VALUES (20, 53);
INSERT INTO stars (user_id, post_id) VALUES (7, 53);
INSERT INTO stars (user_id, post_id) VALUES (1, 53);
INSERT INTO stars (user_id, post_id) VALUES (14, 53);
INSERT INTO stars (user_id, post_id) VALUES (38, 53);
INSERT INTO stars (user_id, post_id) VALUES (35, 53);
INSERT INTO stars (user_id, post_id) VALUES (17, 53);
INSERT INTO stars (user_id, post_id) VALUES (26, 53);
INSERT INTO stars (user_id, post_id) VALUES (10, 53);
INSERT INTO stars (user_id, post_id) VALUES (49, 53);
INSERT INTO stars (user_id, post_id) VALUES (41, 53);
INSERT INTO stars (user_id, post_id) VALUES (36, 54);
INSERT INTO stars (user_id, post_id) VALUES (25, 54);
INSERT INTO stars (user_id, post_id) VALUES (2, 54);
INSERT INTO stars (user_id, post_id) VALUES (25, 54);
INSERT INTO stars (user_id, post_id) VALUES (1, 54);
INSERT INTO stars (user_id, post_id) VALUES (23, 54);
INSERT INTO stars (user_id, post_id) VALUES (1, 54);
INSERT INTO stars (user_id, post_id) VALUES (10, 54);
INSERT INTO stars (user_id, post_id) VALUES (35, 54);
INSERT INTO stars (user_id, post_id) VALUES (12, 54);
INSERT INTO stars (user_id, post_id) VALUES (8, 54);
INSERT INTO stars (user_id, post_id) VALUES (27, 55);
INSERT INTO stars (user_id, post_id) VALUES (11, 55);
INSERT INTO stars (user_id, post_id) VALUES (49, 56);
INSERT INTO stars (user_id, post_id) VALUES (10, 56);
INSERT INTO stars (user_id, post_id) VALUES (45, 56);
INSERT INTO stars (user_id, post_id) VALUES (17, 56);
INSERT INTO stars (user_id, post_id) VALUES (24, 56);
INSERT INTO stars (user_id, post_id) VALUES (13, 56);
INSERT INTO stars (user_id, post_id) VALUES (35, 56);
INSERT INTO stars (user_id, post_id) VALUES (13, 56);
INSERT INTO stars (user_id, post_id) VALUES (40, 56);
INSERT INTO stars (user_id, post_id) VALUES (24, 56);
INSERT INTO stars (user_id, post_id) VALUES (25, 56);
INSERT INTO stars (user_id, post_id) VALUES (46, 56);
INSERT INTO stars (user_id, post_id) VALUES (31, 56);
INSERT INTO stars (user_id, post_id) VALUES (25, 56);
INSERT INTO stars (user_id, post_id) VALUES (28, 56);
INSERT INTO stars (user_id, post_id) VALUES (4, 56);
INSERT INTO stars (user_id, post_id) VALUES (13, 56);
INSERT INTO stars (user_id, post_id) VALUES (37, 56);
INSERT INTO stars (user_id, post_id) VALUES (28, 56);
INSERT INTO stars (user_id, post_id) VALUES (29, 57);
INSERT INTO stars (user_id, post_id) VALUES (49, 59);
INSERT INTO stars (user_id, post_id) VALUES (43, 59);
INSERT INTO stars (user_id, post_id) VALUES (31, 59);
INSERT INTO stars (user_id, post_id) VALUES (6, 59);
INSERT INTO stars (user_id, post_id) VALUES (14, 59);
INSERT INTO stars (user_id, post_id) VALUES (38, 59);
INSERT INTO stars (user_id, post_id) VALUES (22, 59);
INSERT INTO stars (user_id, post_id) VALUES (35, 59);
INSERT INTO stars (user_id, post_id) VALUES (28, 61);
INSERT INTO stars (user_id, post_id) VALUES (9, 61);
INSERT INTO stars (user_id, post_id) VALUES (30, 61);
INSERT INTO stars (user_id, post_id) VALUES (18, 61);
INSERT INTO stars (user_id, post_id) VALUES (34, 61);
INSERT INTO stars (user_id, post_id) VALUES (15, 61);
INSERT INTO stars (user_id, post_id) VALUES (37, 61);
INSERT INTO stars (user_id, post_id) VALUES (45, 61);
INSERT INTO stars (user_id, post_id) VALUES (1, 61);
INSERT INTO stars (user_id, post_id) VALUES (49, 61);
INSERT INTO stars (user_id, post_id) VALUES (16, 61);
INSERT INTO stars (user_id, post_id) VALUES (10, 61);
INSERT INTO stars (user_id, post_id) VALUES (29, 61);
INSERT INTO stars (user_id, post_id) VALUES (8, 61);
INSERT INTO stars (user_id, post_id) VALUES (19, 61);
INSERT INTO stars (user_id, post_id) VALUES (1, 61);
INSERT INTO stars (user_id, post_id) VALUES (40, 61);
INSERT INTO stars (user_id, post_id) VALUES (30, 61);
INSERT INTO stars (user_id, post_id) VALUES (48, 61);
INSERT INTO stars (user_id, post_id) VALUES (41, 61);
INSERT INTO stars (user_id, post_id) VALUES (46, 62);
INSERT INTO stars (user_id, post_id) VALUES (34, 62);
INSERT INTO stars (user_id, post_id) VALUES (25, 62);
INSERT INTO stars (user_id, post_id) VALUES (33, 62);
INSERT INTO stars (user_id, post_id) VALUES (44, 62);
INSERT INTO stars (user_id, post_id) VALUES (43, 62);
INSERT INTO stars (user_id, post_id) VALUES (28, 62);
INSERT INTO stars (user_id, post_id) VALUES (47, 62);
INSERT INTO stars (user_id, post_id) VALUES (16, 62);
INSERT INTO stars (user_id, post_id) VALUES (46, 62);
INSERT INTO stars (user_id, post_id) VALUES (27, 62);
INSERT INTO stars (user_id, post_id) VALUES (8, 62);
INSERT INTO stars (user_id, post_id) VALUES (43, 62);
INSERT INTO stars (user_id, post_id) VALUES (38, 62);
INSERT INTO stars (user_id, post_id) VALUES (32, 62);
INSERT INTO stars (user_id, post_id) VALUES (9, 62);
INSERT INTO stars (user_id, post_id) VALUES (1, 62);
INSERT INTO stars (user_id, post_id) VALUES (8, 62);
INSERT INTO stars (user_id, post_id) VALUES (28, 63);
INSERT INTO stars (user_id, post_id) VALUES (36, 63);
INSERT INTO stars (user_id, post_id) VALUES (43, 63);
INSERT INTO stars (user_id, post_id) VALUES (6, 63);
INSERT INTO stars (user_id, post_id) VALUES (46, 63);
INSERT INTO stars (user_id, post_id) VALUES (15, 63);
INSERT INTO stars (user_id, post_id) VALUES (33, 63);
INSERT INTO stars (user_id, post_id) VALUES (36, 63);
INSERT INTO stars (user_id, post_id) VALUES (46, 63);
INSERT INTO stars (user_id, post_id) VALUES (19, 63);
INSERT INTO stars (user_id, post_id) VALUES (40, 63);
INSERT INTO stars (user_id, post_id) VALUES (37, 63);
INSERT INTO stars (user_id, post_id) VALUES (1, 63);
INSERT INTO stars (user_id, post_id) VALUES (4, 63);
INSERT INTO stars (user_id, post_id) VALUES (7, 63);
INSERT INTO stars (user_id, post_id) VALUES (47, 63);
INSERT INTO stars (user_id, post_id) VALUES (32, 63);
INSERT INTO stars (user_id, post_id) VALUES (3, 64);
INSERT INTO stars (user_id, post_id) VALUES (29, 64);
INSERT INTO stars (user_id, post_id) VALUES (16, 64);
INSERT INTO stars (user_id, post_id) VALUES (9, 64);
INSERT INTO stars (user_id, post_id) VALUES (7, 64);
INSERT INTO stars (user_id, post_id) VALUES (17, 64);
INSERT INTO stars (user_id, post_id) VALUES (23, 64);
INSERT INTO stars (user_id, post_id) VALUES (39, 64);
INSERT INTO stars (user_id, post_id) VALUES (5, 64);
INSERT INTO stars (user_id, post_id) VALUES (48, 64);
INSERT INTO stars (user_id, post_id) VALUES (13, 64);
INSERT INTO stars (user_id, post_id) VALUES (31, 64);
INSERT INTO stars (user_id, post_id) VALUES (29, 64);
INSERT INTO stars (user_id, post_id) VALUES (25, 64);
INSERT INTO stars (user_id, post_id) VALUES (16, 64);
INSERT INTO stars (user_id, post_id) VALUES (39, 64);
INSERT INTO stars (user_id, post_id) VALUES (39, 64);
INSERT INTO stars (user_id, post_id) VALUES (25, 64);
INSERT INTO stars (user_id, post_id) VALUES (30, 64);
INSERT INTO stars (user_id, post_id) VALUES (17, 65);
INSERT INTO stars (user_id, post_id) VALUES (22, 65);
INSERT INTO stars (user_id, post_id) VALUES (23, 65);
INSERT INTO stars (user_id, post_id) VALUES (21, 65);
INSERT INTO stars (user_id, post_id) VALUES (16, 65);
INSERT INTO stars (user_id, post_id) VALUES (36, 65);
INSERT INTO stars (user_id, post_id) VALUES (45, 65);
INSERT INTO stars (user_id, post_id) VALUES (43, 65);
INSERT INTO stars (user_id, post_id) VALUES (26, 65);
INSERT INTO stars (user_id, post_id) VALUES (28, 65);
INSERT INTO stars (user_id, post_id) VALUES (1, 65);
INSERT INTO stars (user_id, post_id) VALUES (40, 66);
INSERT INTO stars (user_id, post_id) VALUES (48, 66);
INSERT INTO stars (user_id, post_id) VALUES (4, 66);
INSERT INTO stars (user_id, post_id) VALUES (49, 66);
INSERT INTO stars (user_id, post_id) VALUES (12, 66);
INSERT INTO stars (user_id, post_id) VALUES (6, 66);
INSERT INTO stars (user_id, post_id) VALUES (31, 66);
INSERT INTO stars (user_id, post_id) VALUES (15, 66);
INSERT INTO stars (user_id, post_id) VALUES (5, 66);
INSERT INTO stars (user_id, post_id) VALUES (8, 66);
INSERT INTO stars (user_id, post_id) VALUES (48, 66);
INSERT INTO stars (user_id, post_id) VALUES (10, 66);
INSERT INTO stars (user_id, post_id) VALUES (49, 66);
INSERT INTO stars (user_id, post_id) VALUES (27, 66);
INSERT INTO stars (user_id, post_id) VALUES (9, 66);
INSERT INTO stars (user_id, post_id) VALUES (18, 66);
INSERT INTO stars (user_id, post_id) VALUES (23, 66);
INSERT INTO stars (user_id, post_id) VALUES (32, 67);
INSERT INTO stars (user_id, post_id) VALUES (27, 67);
INSERT INTO stars (user_id, post_id) VALUES (24, 67);
INSERT INTO stars (user_id, post_id) VALUES (43, 67);
INSERT INTO stars (user_id, post_id) VALUES (27, 67);
INSERT INTO stars (user_id, post_id) VALUES (44, 67);
INSERT INTO stars (user_id, post_id) VALUES (32, 67);
INSERT INTO stars (user_id, post_id) VALUES (28, 67);
INSERT INTO stars (user_id, post_id) VALUES (15, 67);
INSERT INTO stars (user_id, post_id) VALUES (19, 67);
INSERT INTO stars (user_id, post_id) VALUES (30, 67);
INSERT INTO stars (user_id, post_id) VALUES (44, 67);
INSERT INTO stars (user_id, post_id) VALUES (45, 67);
INSERT INTO stars (user_id, post_id) VALUES (35, 67);
INSERT INTO stars (user_id, post_id) VALUES (10, 67);
INSERT INTO stars (user_id, post_id) VALUES (11, 67);
INSERT INTO stars (user_id, post_id) VALUES (35, 68);
INSERT INTO stars (user_id, post_id) VALUES (5, 68);
INSERT INTO stars (user_id, post_id) VALUES (34, 68);
INSERT INTO stars (user_id, post_id) VALUES (28, 68);
INSERT INTO stars (user_id, post_id) VALUES (27, 69);
INSERT INTO stars (user_id, post_id) VALUES (38, 69);
INSERT INTO stars (user_id, post_id) VALUES (15, 69);
INSERT INTO stars (user_id, post_id) VALUES (13, 69);
INSERT INTO stars (user_id, post_id) VALUES (38, 69);
INSERT INTO stars (user_id, post_id) VALUES (18, 69);
INSERT INTO stars (user_id, post_id) VALUES (44, 69);
INSERT INTO stars (user_id, post_id) VALUES (47, 69);
INSERT INTO stars (user_id, post_id) VALUES (5, 69);
INSERT INTO stars (user_id, post_id) VALUES (48, 71);
INSERT INTO stars (user_id, post_id) VALUES (36, 71);
INSERT INTO stars (user_id, post_id) VALUES (2, 71);
INSERT INTO stars (user_id, post_id) VALUES (25, 71);
INSERT INTO stars (user_id, post_id) VALUES (14, 71);
INSERT INTO stars (user_id, post_id) VALUES (34, 71);
INSERT INTO stars (user_id, post_id) VALUES (7, 71);
INSERT INTO stars (user_id, post_id) VALUES (43, 71);
INSERT INTO stars (user_id, post_id) VALUES (27, 71);
INSERT INTO stars (user_id, post_id) VALUES (29, 71);
INSERT INTO stars (user_id, post_id) VALUES (26, 71);
INSERT INTO stars (user_id, post_id) VALUES (47, 71);
INSERT INTO stars (user_id, post_id) VALUES (2, 71);
INSERT INTO stars (user_id, post_id) VALUES (14, 72);
INSERT INTO stars (user_id, post_id) VALUES (41, 72);
INSERT INTO stars (user_id, post_id) VALUES (18, 72);
INSERT INTO stars (user_id, post_id) VALUES (44, 72);
INSERT INTO stars (user_id, post_id) VALUES (11, 72);
INSERT INTO stars (user_id, post_id) VALUES (21, 72);
INSERT INTO stars (user_id, post_id) VALUES (34, 72);
INSERT INTO stars (user_id, post_id) VALUES (1, 72);
INSERT INTO stars (user_id, post_id) VALUES (12, 72);
INSERT INTO stars (user_id, post_id) VALUES (7, 72);
INSERT INTO stars (user_id, post_id) VALUES (13, 73);
INSERT INTO stars (user_id, post_id) VALUES (48, 73);
INSERT INTO stars (user_id, post_id) VALUES (17, 73);
INSERT INTO stars (user_id, post_id) VALUES (27, 73);
INSERT INTO stars (user_id, post_id) VALUES (29, 73);
INSERT INTO stars (user_id, post_id) VALUES (1, 73);
INSERT INTO stars (user_id, post_id) VALUES (22, 73);
INSERT INTO stars (user_id, post_id) VALUES (1, 73);
INSERT INTO stars (user_id, post_id) VALUES (49, 73);
INSERT INTO stars (user_id, post_id) VALUES (1, 73);
INSERT INTO stars (user_id, post_id) VALUES (1, 73);
INSERT INTO stars (user_id, post_id) VALUES (33, 73);
INSERT INTO stars (user_id, post_id) VALUES (13, 73);
INSERT INTO stars (user_id, post_id) VALUES (46, 73);
INSERT INTO stars (user_id, post_id) VALUES (44, 73);
INSERT INTO stars (user_id, post_id) VALUES (12, 74);
INSERT INTO stars (user_id, post_id) VALUES (23, 74);
INSERT INTO stars (user_id, post_id) VALUES (35, 74);
INSERT INTO stars (user_id, post_id) VALUES (43, 74);
INSERT INTO stars (user_id, post_id) VALUES (40, 74);
INSERT INTO stars (user_id, post_id) VALUES (15, 74);
INSERT INTO stars (user_id, post_id) VALUES (24, 74);
INSERT INTO stars (user_id, post_id) VALUES (28, 74);
INSERT INTO stars (user_id, post_id) VALUES (48, 74);
INSERT INTO stars (user_id, post_id) VALUES (43, 74);
INSERT INTO stars (user_id, post_id) VALUES (21, 74);
INSERT INTO stars (user_id, post_id) VALUES (34, 74);
INSERT INTO stars (user_id, post_id) VALUES (9, 74);
INSERT INTO stars (user_id, post_id) VALUES (6, 74);
INSERT INTO stars (user_id, post_id) VALUES (27, 74);
INSERT INTO stars (user_id, post_id) VALUES (7, 74);
INSERT INTO stars (user_id, post_id) VALUES (31, 75);
INSERT INTO stars (user_id, post_id) VALUES (45, 75);
INSERT INTO stars (user_id, post_id) VALUES (7, 75);
INSERT INTO stars (user_id, post_id) VALUES (12, 75);
INSERT INTO stars (user_id, post_id) VALUES (49, 75);
INSERT INTO stars (user_id, post_id) VALUES (3, 75);
INSERT INTO stars (user_id, post_id) VALUES (27, 76);
INSERT INTO stars (user_id, post_id) VALUES (14, 76);
INSERT INTO stars (user_id, post_id) VALUES (43, 76);
INSERT INTO stars (user_id, post_id) VALUES (46, 76);
INSERT INTO stars (user_id, post_id) VALUES (22, 76);
INSERT INTO stars (user_id, post_id) VALUES (1, 76);
INSERT INTO stars (user_id, post_id) VALUES (34, 76);
INSERT INTO stars (user_id, post_id) VALUES (8, 76);
INSERT INTO stars (user_id, post_id) VALUES (45, 76);
INSERT INTO stars (user_id, post_id) VALUES (13, 76);
INSERT INTO stars (user_id, post_id) VALUES (3, 76);
INSERT INTO stars (user_id, post_id) VALUES (31, 76);
INSERT INTO stars (user_id, post_id) VALUES (48, 77);
INSERT INTO stars (user_id, post_id) VALUES (46, 77);
INSERT INTO stars (user_id, post_id) VALUES (12, 77);
INSERT INTO stars (user_id, post_id) VALUES (38, 77);
INSERT INTO stars (user_id, post_id) VALUES (44, 77);
INSERT INTO stars (user_id, post_id) VALUES (49, 77);
INSERT INTO stars (user_id, post_id) VALUES (46, 77);
INSERT INTO stars (user_id, post_id) VALUES (19, 77);
INSERT INTO stars (user_id, post_id) VALUES (35, 77);
INSERT INTO stars (user_id, post_id) VALUES (45, 77);
INSERT INTO stars (user_id, post_id) VALUES (12, 77);
INSERT INTO stars (user_id, post_id) VALUES (36, 77);
INSERT INTO stars (user_id, post_id) VALUES (35, 77);
INSERT INTO stars (user_id, post_id) VALUES (24, 77);
INSERT INTO stars (user_id, post_id) VALUES (7, 77);
INSERT INTO stars (user_id, post_id) VALUES (27, 77);
INSERT INTO stars (user_id, post_id) VALUES (45, 77);
INSERT INTO stars (user_id, post_id) VALUES (23, 77);
INSERT INTO stars (user_id, post_id) VALUES (2, 78);
INSERT INTO stars (user_id, post_id) VALUES (30, 78);
INSERT INTO stars (user_id, post_id) VALUES (15, 78);
INSERT INTO stars (user_id, post_id) VALUES (26, 78);
INSERT INTO stars (user_id, post_id) VALUES (45, 78);
INSERT INTO stars (user_id, post_id) VALUES (43, 78);
INSERT INTO stars (user_id, post_id) VALUES (7, 78);
INSERT INTO stars (user_id, post_id) VALUES (47, 78);
INSERT INTO stars (user_id, post_id) VALUES (33, 78);
INSERT INTO stars (user_id, post_id) VALUES (33, 78);
INSERT INTO stars (user_id, post_id) VALUES (23, 79);
INSERT INTO stars (user_id, post_id) VALUES (1, 79);
INSERT INTO stars (user_id, post_id) VALUES (14, 79);
INSERT INTO stars (user_id, post_id) VALUES (18, 79);
INSERT INTO stars (user_id, post_id) VALUES (12, 79);
INSERT INTO stars (user_id, post_id) VALUES (39, 79);
INSERT INTO stars (user_id, post_id) VALUES (22, 79);
INSERT INTO stars (user_id, post_id) VALUES (6, 79);
INSERT INTO stars (user_id, post_id) VALUES (30, 79);
INSERT INTO stars (user_id, post_id) VALUES (29, 79);
INSERT INTO stars (user_id, post_id) VALUES (13, 79);
INSERT INTO stars (user_id, post_id) VALUES (24, 79);
INSERT INTO stars (user_id, post_id) VALUES (15, 79);
INSERT INTO stars (user_id, post_id) VALUES (12, 79);
INSERT INTO stars (user_id, post_id) VALUES (7, 79);
INSERT INTO stars (user_id, post_id) VALUES (39, 79);
INSERT INTO stars (user_id, post_id) VALUES (36, 79);
INSERT INTO stars (user_id, post_id) VALUES (44, 79);
INSERT INTO stars (user_id, post_id) VALUES (2, 79);
INSERT INTO stars (user_id, post_id) VALUES (27, 81);
INSERT INTO stars (user_id, post_id) VALUES (7, 81);
INSERT INTO stars (user_id, post_id) VALUES (5, 81);
INSERT INTO stars (user_id, post_id) VALUES (22, 81);
INSERT INTO stars (user_id, post_id) VALUES (15, 81);
INSERT INTO stars (user_id, post_id) VALUES (1, 81);
INSERT INTO stars (user_id, post_id) VALUES (47, 81);
INSERT INTO stars (user_id, post_id) VALUES (4, 81);
INSERT INTO stars (user_id, post_id) VALUES (20, 81);
INSERT INTO stars (user_id, post_id) VALUES (18, 81);
INSERT INTO stars (user_id, post_id) VALUES (29, 81);
INSERT INTO stars (user_id, post_id) VALUES (17, 81);
INSERT INTO stars (user_id, post_id) VALUES (28, 81);
INSERT INTO stars (user_id, post_id) VALUES (15, 81);
INSERT INTO stars (user_id, post_id) VALUES (16, 81);
INSERT INTO stars (user_id, post_id) VALUES (22, 81);
INSERT INTO stars (user_id, post_id) VALUES (39, 81);
INSERT INTO stars (user_id, post_id) VALUES (3, 81);
INSERT INTO stars (user_id, post_id) VALUES (30, 81);
INSERT INTO stars (user_id, post_id) VALUES (48, 81);
INSERT INTO stars (user_id, post_id) VALUES (7, 81);
INSERT INTO stars (user_id, post_id) VALUES (16, 81);
INSERT INTO stars (user_id, post_id) VALUES (44, 81);
INSERT INTO stars (user_id, post_id) VALUES (5, 81);
INSERT INTO stars (user_id, post_id) VALUES (18, 81);
INSERT INTO stars (user_id, post_id) VALUES (5, 82);
INSERT INTO stars (user_id, post_id) VALUES (13, 82);
INSERT INTO stars (user_id, post_id) VALUES (45, 82);
INSERT INTO stars (user_id, post_id) VALUES (17, 82);
INSERT INTO stars (user_id, post_id) VALUES (16, 82);
INSERT INTO stars (user_id, post_id) VALUES (33, 82);
INSERT INTO stars (user_id, post_id) VALUES (2, 82);
INSERT INTO stars (user_id, post_id) VALUES (40, 82);
INSERT INTO stars (user_id, post_id) VALUES (37, 82);
INSERT INTO stars (user_id, post_id) VALUES (30, 82);
INSERT INTO stars (user_id, post_id) VALUES (8, 82);
INSERT INTO stars (user_id, post_id) VALUES (2, 82);
INSERT INTO stars (user_id, post_id) VALUES (6, 82);
INSERT INTO stars (user_id, post_id) VALUES (32, 82);
INSERT INTO stars (user_id, post_id) VALUES (39, 82);
INSERT INTO stars (user_id, post_id) VALUES (38, 82);
INSERT INTO stars (user_id, post_id) VALUES (36, 82);
INSERT INTO stars (user_id, post_id) VALUES (43, 84);
INSERT INTO stars (user_id, post_id) VALUES (34, 84);
INSERT INTO stars (user_id, post_id) VALUES (10, 84);
INSERT INTO stars (user_id, post_id) VALUES (8, 84);
INSERT INTO stars (user_id, post_id) VALUES (3, 84);
INSERT INTO stars (user_id, post_id) VALUES (20, 85);
INSERT INTO stars (user_id, post_id) VALUES (5, 85);
INSERT INTO stars (user_id, post_id) VALUES (38, 85);
INSERT INTO stars (user_id, post_id) VALUES (40, 85);
INSERT INTO stars (user_id, post_id) VALUES (36, 85);
INSERT INTO stars (user_id, post_id) VALUES (30, 85);
INSERT INTO stars (user_id, post_id) VALUES (49, 85);
INSERT INTO stars (user_id, post_id) VALUES (29, 85);
INSERT INTO stars (user_id, post_id) VALUES (6, 85);
INSERT INTO stars (user_id, post_id) VALUES (44, 86);
INSERT INTO stars (user_id, post_id) VALUES (16, 86);
INSERT INTO stars (user_id, post_id) VALUES (20, 86);
INSERT INTO stars (user_id, post_id) VALUES (39, 86);
INSERT INTO stars (user_id, post_id) VALUES (19, 86);
INSERT INTO stars (user_id, post_id) VALUES (31, 86);
INSERT INTO stars (user_id, post_id) VALUES (45, 86);
INSERT INTO stars (user_id, post_id) VALUES (9, 86);
INSERT INTO stars (user_id, post_id) VALUES (1, 86);
INSERT INTO stars (user_id, post_id) VALUES (41, 86);
INSERT INTO stars (user_id, post_id) VALUES (31, 86);
INSERT INTO stars (user_id, post_id) VALUES (32, 87);
INSERT INTO stars (user_id, post_id) VALUES (15, 87);
INSERT INTO stars (user_id, post_id) VALUES (47, 87);
INSERT INTO stars (user_id, post_id) VALUES (33, 87);
INSERT INTO stars (user_id, post_id) VALUES (3, 87);
INSERT INTO stars (user_id, post_id) VALUES (5, 87);
INSERT INTO stars (user_id, post_id) VALUES (43, 87);
INSERT INTO stars (user_id, post_id) VALUES (36, 87);
INSERT INTO stars (user_id, post_id) VALUES (22, 87);
INSERT INTO stars (user_id, post_id) VALUES (8, 87);
INSERT INTO stars (user_id, post_id) VALUES (3, 87);
INSERT INTO stars (user_id, post_id) VALUES (2, 87);
INSERT INTO stars (user_id, post_id) VALUES (18, 87);
INSERT INTO stars (user_id, post_id) VALUES (32, 87);
INSERT INTO stars (user_id, post_id) VALUES (15, 87);
INSERT INTO stars (user_id, post_id) VALUES (28, 87);
INSERT INTO stars (user_id, post_id) VALUES (24, 88);
INSERT INTO stars (user_id, post_id) VALUES (49, 88);
INSERT INTO stars (user_id, post_id) VALUES (2, 88);
INSERT INTO stars (user_id, post_id) VALUES (4, 88);
INSERT INTO stars (user_id, post_id) VALUES (41, 88);
INSERT INTO stars (user_id, post_id) VALUES (7, 88);
INSERT INTO stars (user_id, post_id) VALUES (37, 88);
INSERT INTO stars (user_id, post_id) VALUES (28, 89);
INSERT INTO stars (user_id, post_id) VALUES (26, 89);
INSERT INTO stars (user_id, post_id) VALUES (25, 89);
INSERT INTO stars (user_id, post_id) VALUES (13, 89);
INSERT INTO stars (user_id, post_id) VALUES (34, 89);
INSERT INTO stars (user_id, post_id) VALUES (23, 89);
INSERT INTO stars (user_id, post_id) VALUES (12, 89);
INSERT INTO stars (user_id, post_id) VALUES (46, 89);
INSERT INTO stars (user_id, post_id) VALUES (21, 89);
INSERT INTO stars (user_id, post_id) VALUES (41, 89);
INSERT INTO stars (user_id, post_id) VALUES (28, 89);
INSERT INTO stars (user_id, post_id) VALUES (3, 89);
INSERT INTO stars (user_id, post_id) VALUES (25, 89);
INSERT INTO stars (user_id, post_id) VALUES (45, 89);
INSERT INTO stars (user_id, post_id) VALUES (15, 91);
INSERT INTO stars (user_id, post_id) VALUES (41, 91);
INSERT INTO stars (user_id, post_id) VALUES (32, 91);
INSERT INTO stars (user_id, post_id) VALUES (49, 91);
INSERT INTO stars (user_id, post_id) VALUES (44, 91);
INSERT INTO stars (user_id, post_id) VALUES (46, 91);
INSERT INTO stars (user_id, post_id) VALUES (25, 91);
INSERT INTO stars (user_id, post_id) VALUES (25, 91);
INSERT INTO stars (user_id, post_id) VALUES (35, 91);
INSERT INTO stars (user_id, post_id) VALUES (13, 91);
INSERT INTO stars (user_id, post_id) VALUES (22, 91);
INSERT INTO stars (user_id, post_id) VALUES (20, 91);
INSERT INTO stars (user_id, post_id) VALUES (38, 91);
INSERT INTO stars (user_id, post_id) VALUES (11, 91);
INSERT INTO stars (user_id, post_id) VALUES (41, 91);
INSERT INTO stars (user_id, post_id) VALUES (16, 91);
INSERT INTO stars (user_id, post_id) VALUES (35, 91);
INSERT INTO stars (user_id, post_id) VALUES (5, 91);
INSERT INTO stars (user_id, post_id) VALUES (40, 91);
INSERT INTO stars (user_id, post_id) VALUES (10, 92);
INSERT INTO stars (user_id, post_id) VALUES (48, 92);
INSERT INTO stars (user_id, post_id) VALUES (37, 92);
INSERT INTO stars (user_id, post_id) VALUES (34, 92);
INSERT INTO stars (user_id, post_id) VALUES (1, 92);
INSERT INTO stars (user_id, post_id) VALUES (44, 92);
INSERT INTO stars (user_id, post_id) VALUES (32, 92);
INSERT INTO stars (user_id, post_id) VALUES (7, 92);
INSERT INTO stars (user_id, post_id) VALUES (40, 92);
INSERT INTO stars (user_id, post_id) VALUES (25, 92);
INSERT INTO stars (user_id, post_id) VALUES (24, 93);
INSERT INTO stars (user_id, post_id) VALUES (3, 93);
INSERT INTO stars (user_id, post_id) VALUES (49, 93);
INSERT INTO stars (user_id, post_id) VALUES (23, 93);
INSERT INTO stars (user_id, post_id) VALUES (13, 93);
INSERT INTO stars (user_id, post_id) VALUES (4, 93);
INSERT INTO stars (user_id, post_id) VALUES (29, 93);
INSERT INTO stars (user_id, post_id) VALUES (10, 94);
INSERT INTO stars (user_id, post_id) VALUES (46, 94);
INSERT INTO stars (user_id, post_id) VALUES (3, 94);
INSERT INTO stars (user_id, post_id) VALUES (9, 94);
INSERT INTO stars (user_id, post_id) VALUES (49, 95);
INSERT INTO stars (user_id, post_id) VALUES (39, 95);
INSERT INTO stars (user_id, post_id) VALUES (12, 95);
INSERT INTO stars (user_id, post_id) VALUES (31, 95);
INSERT INTO stars (user_id, post_id) VALUES (34, 95);
INSERT INTO stars (user_id, post_id) VALUES (22, 95);
INSERT INTO stars (user_id, post_id) VALUES (9, 95);
INSERT INTO stars (user_id, post_id) VALUES (10, 95);
INSERT INTO stars (user_id, post_id) VALUES (29, 95);
INSERT INTO stars (user_id, post_id) VALUES (6, 95);
INSERT INTO stars (user_id, post_id) VALUES (46, 95);
INSERT INTO stars (user_id, post_id) VALUES (3, 95);
INSERT INTO stars (user_id, post_id) VALUES (21, 95);
INSERT INTO stars (user_id, post_id) VALUES (12, 95);
INSERT INTO stars (user_id, post_id) VALUES (15, 96);
INSERT INTO stars (user_id, post_id) VALUES (47, 96);
INSERT INTO stars (user_id, post_id) VALUES (41, 96);
INSERT INTO stars (user_id, post_id) VALUES (5, 96);
INSERT INTO stars (user_id, post_id) VALUES (19, 96);
INSERT INTO stars (user_id, post_id) VALUES (36, 96);
INSERT INTO stars (user_id, post_id) VALUES (19, 96);
INSERT INTO stars (user_id, post_id) VALUES (23, 96);
INSERT INTO stars (user_id, post_id) VALUES (31, 96);
INSERT INTO stars (user_id, post_id) VALUES (39, 96);
INSERT INTO stars (user_id, post_id) VALUES (16, 96);
INSERT INTO stars (user_id, post_id) VALUES (32, 96);
INSERT INTO stars (user_id, post_id) VALUES (26, 96);
INSERT INTO stars (user_id, post_id) VALUES (31, 97);
INSERT INTO stars (user_id, post_id) VALUES (32, 97);
INSERT INTO stars (user_id, post_id) VALUES (39, 98);
INSERT INTO stars (user_id, post_id) VALUES (1, 98);
INSERT INTO stars (user_id, post_id) VALUES (20, 99);
INSERT INTO stars (user_id, post_id) VALUES (23, 99);
INSERT INTO stars (user_id, post_id) VALUES (41, 99);
